import { createElement } from '@lwc/engine-dom';
import Kpn_AvailableProducts from 'c/kpn_AvailableProducts';

describe('c-kpn-available-products', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-kpn-available-products', {
            is: Kpn_AvailableProducts
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});